from app.models.models import (
    Base,
    Usuario,
    TokenSesion,
    TokenRecuperacion,
    # PerfilMorfologico,
    # PreferenciaEstilo,
    AnalisisMorfologico,
    ReglasRecomendacion,
    RecomendacionGenerada,
    Marca,
    Categoria,
    Color,
    Talla,
    Producto,
    ImagenProducto,
    ProductoEtiquetaMorfologica,
    Inventario,
    Carrito,
    CarritoItem,
    Orden,
    OrdenItem,
    Comprobante,
    HistorialProducto,
    RecomendacionIA,
    HistorialReporte,
)
from app.models.preference_model import PreferenciasUsuario
from app.models.style_model import Estilo

__all__ = [
    "Base",
    "Usuario",
    "TokenSesion",
    "TokenRecuperacion",
    "PerfilMorfologico",
    # "PreferenciaEstilo",
    "AnalisisMorfologico",
    "ReglasRecomendacion",
    "RecomendacionGenerada",
    "Marca",
    "Categoria",
    "Color",
    "Talla",
    "Producto",
    "ImagenProducto",
    "ProductoEtiquetaMorfologica",
    "Inventario",
    "Carrito",
    "CarritoItem",
    "Orden",
    "OrdenItem",
    "Comprobante",
    "HistorialProducto",
    "RecomendacionIA",
    "HistorialReporte",
    "PreferenciasUsuario",
    "Estilo",
]
