import { test, expect } from '@playwright/test';

test('Test de flujo de compra', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.getByRole('link', { name: 'Iniciar sesión' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).fill('marcoforsamge@gmail.com');
  await page.getByRole('textbox', { name: 'Correo electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo electrónico' }).fill('marcoforsage@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('123456789');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('button', { name: 'Camisas y Blusas' }).click();
  await page.getByRole('button', { name: 'Camisas y Blusas' }).click();
  await page.getByRole('button', { name: 'Chaquetas', exact: true }).click();
  await page.getByRole('button', { name: 'Chaquetas', exact: true }).click();
  await page.getByRole('button', { name: 'Ver Detalles' }).first().click();
  await page.getByRole('button', { name: 'L', exact: true }).click();
  await page.getByRole('button', { name: 'Negro' }).click();
  await page.getByRole('button', { name: 'Añadir al Carrito' }).first().click();
  await page.getByRole('link', { name: '1' }).click();
  await page.getByRole('button', { name: 'Proceder al Pago' }).click();
  await page.getByRole('textbox', { name: 'Quevedo' }).click();
  await page.getByRole('textbox', { name: 'Quevedo' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Quevedo' }).fill('SA');
  await page.getByRole('textbox', { name: 'Quevedo' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Quevedo' }).fill('Santo ');
  await page.getByRole('textbox', { name: 'Quevedo' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Quevedo' }).fill('Santo D');
  await page.getByRole('textbox', { name: 'Quevedo' }).press('Tab');
  await page.getByRole('textbox', { name: 'Quevedo' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Quevedo' }).fill('Santo Do');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('');
  await page.getByRole('textbox', { name: 'Quevedo' }).click();
  await page.getByRole('textbox', { name: 'Quevedo' }).fill('Santo Domingo');
  await page.getByRole('textbox', { name: 'Los Ríos' }).click();
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('S');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('Santo ');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('Santo D');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('Santo Domingo ');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('Santo Domingo de los ');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('Santo Domingo de los T');
  await page.getByRole('textbox', { name: 'Los Ríos' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Los Ríos' }).fill('Santo Domingo de los Tsachilas');
  await page.getByRole('textbox', { name: '120501' }).click();
  await page.getByRole('textbox', { name: '120501' }).fill('230101');
  await page.getByRole('button', { name: 'Continuar al pago' }).click();
  await page.getByRole('button', { name: 'Proceder al pago' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('marcoforsage@gmail.com');
  await page.getByRole('textbox', { name: 'Card number' }).click();
  await page.getByRole('textbox', { name: 'Card number' }).fill('4242 4242 4242 42422');
  await page.getByRole('textbox', { name: 'Expiration' }).click();
  await page.getByRole('textbox', { name: 'Expiration' }).fill('03 / 29');
  await page.getByRole('textbox', { name: 'CVC' }).click();
  await page.getByRole('textbox', { name: 'CVC' }).fill('123');
  await page.getByRole('textbox', { name: 'Cardholder name' }).click();
  await page.getByRole('textbox', { name: 'Cardholder name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cardholder name' }).fill('T');
  await page.getByRole('textbox', { name: 'Cardholder name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cardholder name' }).fill('Tibisay ');
  await page.getByRole('textbox', { name: 'Cardholder name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cardholder name' }).fill('Tibisay N');
  await page.getByRole('textbox', { name: 'Cardholder name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cardholder name' }).fill('Tibisay Naveda');
  await page.getByTestId('hosted-payment-submit-button').click();
  await page.getByRole('link', { name: 'Ver detalle de orden' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar Recibo PDF' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Catálogo' }).click();
});
